name: "RFXCOM Node.js Bridge"
description: "Bridge Node.js pour la communication RFXCOM via le package node-rfxcom"
version: "1.1.1"
slug: "rfxcom-nodejs-bridge"
init: false
startup: services
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
options:
  serial_port: "/dev/ttyUSB0"
  log_level: "info"
schema:
  serial_port: device(subsystem=tty)?
  log_level: list(error|warn|info|debug)?